-- 메뉴
CREATE TABLE MENU (
	MCODE VARCHAR2(30) NOT NULL,
	MNAME VARCHAR2(40) NOT NULL,
	MURL VARCHAR2(150) NOT NULL,
	MICON VARCHAR2(100) NULL,
	JTEXT VARCHAR2(1500) NULL,
	UPCODE VARCHAR2(40) NOT NULL,
	MLEVEL NUMBER NULL,
	ISNAV NUMBER NULL
);

-- 메뉴
ALTER TABLE MENU
	ADD CONSTRAINT MENU -- 메뉴
	PRIMARY KEY (
	MCODE -- MCODE
	);

-- 자유게시판
CREATE TABLE FREE_BOARD (
	FNO NUMBER NOT NULL,
	TITLE VARCHAR2(30) NOT NULL,
	CONTENT VARCHAR2(3200) NOT NULL,
	REGDATE DATE NOT NULL,
	VIEWCNT NUMBER NULL,
	UPDATEDATE DATE NULL,
	ID VARCHAR2(50) NULL
);

-- 자유게시판
ALTER TABLE FREE_BOARD
	ADD CONSTRAINT FREE_BOARD -- 자유게시판
	PRIMARY KEY (
	FNO -- FNO
	);

-- 질문게시판
CREATE TABLE Q_BOARD (
	QNO NUMBER NOT NULL,
	TITLE VARCHAR2(30) NOT NULL,
	CONTENT VARCHAR2(3200) NOT NULL,
	REGDATE DATE NOT NULL,
	VIEWCNT NUMBER NULL,
	UPDATEDATE DATE NULL,
	ID VARCHAR2(50) NULL
);

-- 질문게시판
ALTER TABLE Q_BOARD
	ADD CONSTRAINT Q_BOARD -- 질문게시판
	PRIMARY KEY (
	QNO -- QNO
	);

-- 자료실
CREATE TABLE PDS (
	PNO NUMBER NOT NULL,
	TITLE VARCHAR2(50) NOT NULL,
	CONTENT VARCHAR2(3200) NOT NULL,
	REGDATE DATE NOT NULL,
	VIEWCNT NUMBER NULL,
	UPDATEDATE DATE NULL,
	ID VARCHAR2(50) NULL
);

-- 자료실
ALTER TABLE PDS
	ADD CONSTRAINT DATA_ROOM -- 자료실
	PRIMARY KEY (
	PNO -- PNO
	);

-- 공지사항
CREATE TABLE NOTICE (
	NNO NUMBER NOT NULL,
	TITLE VARCHAR2(50) NOT NULL,
	CONTENT VARCHAR2(3200) NOT NULL,
	REGDATE DATE NOT NULL,
	VIEWCNT NUMBER NULL,
	UPDATEDATE DATE NULL,
	ID VARCHAR2(50) NULL
);

-- 공지사항
ALTER TABLE NOTICE
	ADD CONSTRAINT NOTICE -- 공지사항
	PRIMARY KEY (
	NNO -- NNO
	);

-- 취업게시판
CREATE TABLE WORK_BOARD (
	WNO NUMBER NOT NULL,
	TITLE VARCHAR2(30) NOT NULL,
	CONTENT VARCHAR2(3200) NOT NULL,
	REGDATE DATE NOT NULL,
	VIEWCNT NUMBER NULL,
	UPDATEDATE DATE NULL,
	ID VARCHAR2(50) NULL
);

-- 취업게시판
ALTER TABLE WORK_BOARD
	ADD CONSTRAINT WORK_BOARD -- 취업게시판
	PRIMARY KEY (
	WNO -- WNO
	);

-- 자유게시판답변 
CREATE TABLE F_REPLY (
	F_RNO NUMBER NOT NULL,
	REPLYTEXT VARCHAR2(600) NOT NULL,
	REGDATE DATE NOT NULL,
	UPDATEDATE DATE NULL,
	FNO NUMBER NULL,
	ID VARCHAR2(50) NULL
);

-- 자유게시판답변 
ALTER TABLE F_REPLY
	ADD CONSTRAINT PK_F_REPLY -- 자유게시판답변  기본키
	PRIMARY KEY (
	F_RNO -- F_RNO
	);

-- 질문게시판답변
CREATE TABLE Q_REPLY (
	Q_RNO NUMBER NOT NULL,
	REPLYTEXT VARCHAR2(600) NOT NULL,
	REGDATE DATE NOT NULL,
	UPDATEDATE DATE NULL,
	QNO NUMBER NULL,
	ID VARCHAR2(50) NULL
);

-- 질문게시판답변
ALTER TABLE Q_REPLY
	ADD CONSTRAINT Q_REPLY -- 질문게시판답변
	PRIMARY KEY (
	Q_RNO -- Q_RNO
	);

-- 취업게시판답변
CREATE TABLE W_REPLY (
	W_RNO NUMBER NOT NULL,
	REPLYTEXT VARCHAR2(600) NOT NULL,
	REGDATE DATE NOT NULL,
	UPDATEDATE DATE NULL,
	WNO NUMBER NULL,
	ID VARCHAR2(50) NULL
);

-- 취업게시판답변
ALTER TABLE W_REPLY
	ADD CONSTRAINT W_REPLY -- 취업게시판답변
	PRIMARY KEY (
	W_RNO -- W_RNO
	);

-- 멤버
CREATE TABLE MEMBER (
	ID VARCHAR2(50) NOT NULL,
	PWD VARCHAR2(75) NOT NULL,
	EMAIL VARCHAR2(60) NOT NULL,
	PHONE VARCHAR2(35) NULL,
	ADDRESS VARCHAR2(200) NULL,
	NAME VARCHAR2(20) NOT NULL
);

-- 멤버
ALTER TABLE MEMBER
	ADD CONSTRAINT PK_MEMBER -- 멤버 기본키
	PRIMARY KEY (
	ID -- ID
	);

-- 자료실파일테이블
CREATE TABLE P_FILE (
	P_ANO NUMBER NOT NULL,
	UPLOADPATH VARCHAR2(500) NOT NULL,
	FILENAME VARCHAR2(200) NOT NULL,
	FILETYPE VARCHAR2(50) NOT NULL,
	PNO NUMBER NULL
);

-- 자료실파일테이블
ALTER TABLE P_FILE
	ADD CONSTRAINT DR_FILE -- 자료실파일테이블
	PRIMARY KEY (
	P_ANO -- P_ANO
	);

-- 취업파일테이블
CREATE TABLE WORK_FILE (
	W_ANO NUMBER NOT NULL,
	UPLOADPATH VARCHAR2(500) NOT NULL,
	FILENAME VARCHAR2(200) NOT NULL,
	FILETYPE VARCHAR2(50) NOT NULL,
	WNO NUMBER NULL
);

-- 취업파일테이블
ALTER TABLE WORK_FILE
	ADD CONSTRAINT PK_WORK_FILE -- 취업파일테이블 기본키
	PRIMARY KEY (
	W_ANO -- W_ANO
	);

-- 자유게시판
ALTER TABLE FREE_BOARD
	ADD CONSTRAINT FK_MEMBER_TO_FREE_BOARD -- 멤버 -> 자유게시판
	FOREIGN KEY (
	ID -- ID
	)
	REFERENCES MEMBER ( -- 멤버
	ID -- ID
	);

-- 질문게시판
ALTER TABLE Q_BOARD
	ADD CONSTRAINT FK_MEMBER_TO_Q_BOARD -- 멤버 -> 질문게시판
	FOREIGN KEY (
	ID -- ID
	)
	REFERENCES MEMBER ( -- 멤버
	ID -- ID
	);

-- 자료실
ALTER TABLE PDS
	ADD CONSTRAINT FK_MEMBER_TO_PDS -- 멤버 -> 자료실
	FOREIGN KEY (
	ID -- ID
	)
	REFERENCES MEMBER ( -- 멤버
	ID -- ID
	);

-- 공지사항
ALTER TABLE NOTICE
	ADD CONSTRAINT FK_MEMBER_TO_NOTICE -- 멤버 -> 공지사항
	FOREIGN KEY (
	ID -- ID
	)
	REFERENCES MEMBER ( -- 멤버
	ID -- ID
	);

-- 취업게시판
ALTER TABLE WORK_BOARD
	ADD CONSTRAINT FK_MEMBER_TO_WORK_BOARD -- 멤버 -> 취업게시판
	FOREIGN KEY (
	ID -- ID
	)
	REFERENCES MEMBER ( -- 멤버
	ID -- ID
	);

-- 자유게시판답변 
ALTER TABLE F_REPLY
	ADD CONSTRAINT FK_FREE_BOARD_TO_F_REPLY -- 자유게시판 -> 자유게시판답변 
	FOREIGN KEY (
	FNO -- FNO
	)
	REFERENCES FREE_BOARD ( -- 자유게시판
	FNO -- FNO
	);

-- 자유게시판답변 
ALTER TABLE F_REPLY
	ADD CONSTRAINT FK_MEMBER_TO_F_REPLY -- 멤버 -> 자유게시판답변 
	FOREIGN KEY (
	ID -- ID
	)
	REFERENCES MEMBER ( -- 멤버
	ID -- ID
	);

-- 질문게시판답변
ALTER TABLE Q_REPLY
	ADD CONSTRAINT FK_Q_BOARD_TO_Q_REPLY -- 질문게시판 -> 질문게시판답변
	FOREIGN KEY (
	QNO -- QNO
	)
	REFERENCES Q_BOARD ( -- 질문게시판
	QNO -- QNO
	);

-- 질문게시판답변
ALTER TABLE Q_REPLY
	ADD CONSTRAINT FK_MEMBER_TO_Q_REPLY -- 멤버 -> 질문게시판답변
	FOREIGN KEY (
	ID -- ID
	)
	REFERENCES MEMBER ( -- 멤버
	ID -- ID
	);

-- 취업게시판답변
ALTER TABLE W_REPLY
	ADD CONSTRAINT FK_WORK_BOARD_TO_W_REPLY -- 취업게시판 -> 취업게시판답변
	FOREIGN KEY (
	WNO -- WNO
	)
	REFERENCES WORK_BOARD ( -- 취업게시판
	WNO -- WNO
	);

-- 취업게시판답변
ALTER TABLE W_REPLY
	ADD CONSTRAINT FK_MEMBER_TO_W_REPLY -- 멤버 -> 취업게시판답변
	FOREIGN KEY (
	ID -- ID
	)
	REFERENCES MEMBER ( -- 멤버
	ID -- ID
	);

-- 자료실파일테이블
ALTER TABLE P_FILE
	ADD CONSTRAINT FK_PDS_TO_P_FILE -- 자료실 -> 자료실파일테이블
	FOREIGN KEY (
	PNO -- PNO
	)
	REFERENCES PDS ( -- 자료실
	PNO -- PNO
	);

-- 취업파일테이블
ALTER TABLE WORK_FILE
	ADD CONSTRAINT FK_WORK_BOARD_TO_WORK_FILE -- 취업게시판 -> 취업파일테이블
	FOREIGN KEY (
	WNO -- WNO
	)
	REFERENCES WORK_BOARD ( -- 취업게시판
	WNO -- WNO
	);